name: Publish (Release)

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:


permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Clone
      shell: bash
      run: git clone --recurse-submodules https://github.com/Z4ee/StarRail-S-GC
        
    - name: Build solution
      working-directory: ./StarRail-S-GC
      env:
        SOLUTION_FILE_PATH: ./HSR-GC.sln
        BUILD_CONFIGURATION: Release
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
        
    - name: Removing unused files
      shell: bash
      run: |
        ls -lR --group-directories-first
        rm -rf ./StarRail-S-GC/x64/Release/*.pdb
        rm -rf ./StarRail-S-GC/x64/Release/*.ipdb
        rm -rf ./StarRail-S-GC/x64/Release/*.obj
        rm -rf ./StarRail-S-GC/x64/Release/*.iobj
        rm -rf ./StarRail-S-GC/x64/Release/*.txt
        rm -rf ./StarRail-S-GC/x64/Release/*.recipe
        rm -rf ./StarRail-S-GC/x64/Release/*.tlog
      
    - name: Upload to github
      uses: actions/upload-artifact@v3.1.2
      with:
        name: StarRail-GC-Release
        path: ./StarRail-S-GC/x64/Release/*
        if-no-files-found: error
